export const items = {
    POPULAR: [
      {
        id: '2rsp',
        name: 'Ranch Seafood Pizza',
        price: 150,
        img: 'https://png.pngtree.com/png-clipart/20210808/original/pngtree-big-pizza-png-png-image_6611417.png',
        quantity: 0,
        description:
          'thin crust, Mozarella cheese, vegetables, shrimps & fish with ranch sauce.',
      },
  
      {
        id: '3ppcp',
        name: 'Per Perri Chiken Pizza',
        price: 90,
        img: 'https://toppng.com/uploads/preview/izza-icon-clipart-crust-peri-peri-chicken-pizza-11563652620whirtz2rfi.png',
        quantity: 0,
        description:
          'thick crust, Mozarella cheese, vegetables, mushrooms & Per Perri chicken with red sauce.',
      },
      {
        id: '3bcb',
        name: 'Bacon Cheese Burger',
        price: 70,
        img: 'https://toppng.com/uploads/preview/burger-vector-bacon-double-bacon-burger-ki-11563627183lpwwvimtqb.png',
        quantity: 0,
        description:
          'thin crust, Mozarella Parmesan mix & pepperoni with red sauce.',
      },
      {
        id: '2tb',
        name: 'Tower Burger',
        price: 80,
        img: 'https://www.pngfind.com/pngs/m/469-4697896_bacon-burger-just-burger-malta-cheeseburger-hd-png.png',
        quantity: 0,
        description: 'cheese, tomato, onions, lettuce, bacon, ketchup.',
      },
      {
        id: '2sc',
        name: 'Strawberry Crepe',
        price: 40,
        img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtzwuZOYQneCGqsEpEbJtDkmReL5c4qg8cxxWxwvt8zjX1XhhFs9QE1TaW0rdSNyLPQDw&usqp=CAU',
        quantity: 0,
        description: 'strawberry, maple cyrup, whipped cream.',
      },
      {
        id: '3cbc',
        name: 'Choco Banana Crepe',
        price: 40,
        img: 'https://mpng.subpng.com/20180530/rio/kisspng-frosting-icing-pancake-crpe-torte-white-chocol-5b0f3059379795.6304265015277220732277.jpg',
        quantity: 0,
        description: 'chocolate filling.',
      },
    ],
    PIZZA: [
      {
        id: '1pp',
        name: 'Pepperoni Pizza',
        price: 90,
        img: 'https://toppng.com/uploads/preview/transparent-png-pizza-pepperoni-pizza-1156311772084svgw9hld.png',
        quantity: 0,
        description:
          'thin crust, Mozarella Parmesan mix & pepperoni with red sauce.',
      },
      {
        id: '2rsp',
        name: 'Ranch Seafood Pizza',
        price: 150,
        img: 'https://png.pngtree.com/png-clipart/20210808/original/pngtree-big-pizza-png-png-image_6611417.png',
        quantity: 0,
        description:
          'thin crust, Mozarella, vegetables, shrimps & fish with ranch sauce.',
      },
      {
        id: '3ppcp',
        name: 'Per Perri Chiken Pizza',
        price: 100,
        img: 'https://toppng.com/uploads/preview/izza-icon-clipart-crust-peri-peri-chicken-pizza-11563652620whirtz2rfi.png',
        quantity: 0,
        description:
          'thick crust, Mozarella, olives, mushroom & Per Perri chicken with red sauce.',
      },
      {
        id: '4rcp',
        name: 'Ranch Chicken Pizza',
        price: 90,
        img: 'https://png.pngtree.com/png-clipart/20201226/ourmid/pngtree-full-size-chicken-pizza-png-image_2642197.jpg',
        description: 'thick crust, Mozarella, pepper & chicken with ranch sauce.',
      },
      {
        id: '5vp',
        name: 'Veggie Pizza',
        price: 80,
        img: 'https://toppng.com/uploads/preview/tropical-veg-pizza-hut-11563203677euwbnqn7hy.png',
        description: 'thin crust, Mozarella & vegetables with red sauce.',
      },
      {
        id: '6mp',
        name: 'Margarita Pizza',
        price: 70,
        img: 'https://www.vhv.rs/dpng/d/288-2881053_margherita-pizza-transparent-hd-png-download.png',
        description: 'thick crust & Mozarella with red sauce.',
      },
    ],
    BURGER: [
      {
        id: '3bcb',
        name: 'Bacon Cheese Burger',
        price: 70,
        img: 'https://toppng.com/uploads/preview/burger-vector-bacon-double-bacon-burger-ki-11563627183lpwwvimtqb.png',
        quantity: 0,
        description: 'cheese, tomato, onions, lettuce, bacon, ketchup.',
      },
      {
        id: '2tb',
        name: 'Tower Burger',
        price: 80,
        img: 'https://www.pngfind.com/pngs/m/469-4697896_bacon-burger-just-burger-malta-cheeseburger-hd-png.png',
        quantity: 0,
        description: 'cheese, tomato, onions, lettuce, bacon, ketchup.',
      },
      {
        id: '3vmb',
        name: 'Veggie mix Burger',
        price: 75,
        img: 'https://toppng.com//public/uploads/preview/burger-11528340630dx5paxa77f.png',
        quantity: 0,
        description: 'cheese, tomato, onions, lettuce, broccolli, ketchup.',
      },
      {
        id: '4msb',
        name: 'Tower Burger',
        price: 80,
        img: 'https://e7.pngegg.com/pngimages/190/977/png-clipart-cheeseburger-hamburger-veggie-burger-patty-fast-food-meat-food-recipe.png',
        quantity: 0,
        description: 'cheese, mushroom , pepper sauce.',
      },
    ],
    CREPE: [
      {
        id: '1cc',
        name: 'Chocolate Crepe',
        price: 40,
        img: 'https://www.pikpng.com/pngl/m/537-5372384_silverqueen-crepes-double-choco-crispy-d-crepes-clipart.png',
        quantity: 0,
        description: 'chocolate filling.',
      },
      {
        id: '2sc',
        name: 'Strawberry Crepe',
        price: 40,
        img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtzwuZOYQneCGqsEpEbJtDkmReL5c4qg8cxxWxwvt8zjX1XhhFs9QE1TaW0rdSNyLPQDw&usqp=CAU',
        quantity: 0,
        description: 'strawberry, maple cyrup, whipped cream.',
      },
      {
        id: '3cbc',
        name: 'Choco Banana Crepe',
        price: 40,
        img: 'https://mpng.subpng.com/20180530/rio/kisspng-frosting-icing-pancake-crpe-torte-white-chocol-5b0f3059379795.6304265015277220732277.jpg',
        quantity: 0,
        description: 'chocolate filling.',
      },
    ],
    DRINKS: [
      {
        id: '1dpc',
        name: 'Pepsi',
        price: 15,
        img: 'https://www.pinclipart.com/picdir/middle/361-3613612_pepsi-can-png-pepsi-and-coca-cola-logo.png',
        quantity: 0,
        description: 'can, bottle or machine fill.',
      },
      {
        id: '1d7u',
        name: '7up',
        price: 15,
        img: 'https://toppng.com/uploads/preview/7up-can-11538598609dqjkdandfy.png',
        quantity: 0,
        description: 'can, bottle or machine fill.',
      },
      {
        id: '1dmo',
        name: 'Mirinda Orange',
        price: 15,
        img: 'https://e7.pngegg.com/pngimages/391/688/png-clipart-orange-drink-fizzy-drinks-mirinda-orange-soft-drink-flavor-by-bob-holmes-jonathan-yen-narrator-9781515966647-bucket-of-beer-burgers-gadget-orange.png',
        quantity: 0,
        description: 'can, bottle or machine fill.',
      },
      {
        id: '1ddp',
        name: 'Dr.Pepper',
        price: 15,
        img: 'https://toppng.com/uploads/preview/dr-pepper-can-png-dr-pepper-12-fl-oz-cans-4-pack-11563035766yatq3jwdxo.png',
        quantity: 0,
        description: 'can, bottle or machine fill.',
      },
    ],
  };